/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gt.edu.umg.Ventanas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author rober
 */
public class ArbolBinario extends javax.swing.JPanel {

    /**
     * Creates new form Page1
     */
    public ArbolBinario() {
        initComponents();

        content.setBackground(new Color(250, 252, 253));
    }

    public void File_Reader(String ruta, JLabel Texto) {
        try {
            File archivo = new File(ruta);
            FileReader lector = new FileReader(archivo);
            BufferedReader buffer = new BufferedReader(lector);
            StringBuilder mensajeCompleto = new StringBuilder(); // Construir el mensaje completo
            String linea;
            boolean esValido = true; // Bandera para indicar si el archivo es válido

            while ((linea = buffer.readLine()) != null) {
                System.out.println(linea);
                // Validar la línea actual
                if (!validarLinea(linea)) {
                    esValido = false;
                    break; // Si la línea no es válida, salir del bucle
                }
                mensajeCompleto.append(linea).append("\n"); // Agregar cada línea al mensaje completo
            }
            buffer.close();

            if (esValido) {
                // Configurar el texto en el componente Texto
                Texto.setText(mensajeCompleto.toString());
            } else {
                // Mostrar mensaje de error
                Texto.setText("El formato del archivo debe contener solo números y comas.");
            }
        } catch (Exception e) {
            System.out.println("Error al cargar el archivo: " + e.getMessage());
        }
    }

    private boolean validarLinea(String linea) {
        // Utilizar una expresión regular para validar que la línea contiene solo números y comas

        return linea.matches("[0-9,]+")
                && !linea.startsWith(",")
                && !linea.endsWith(",")
                && !linea.contains(",,");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        Buton3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Buton2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        Buton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Buton4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Buton5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Buton6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setBackground(new java.awt.Color(250, 252, 253));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(204, 204, 204));

        Buton3.setBackground(new java.awt.Color(250, 252, 253));
        Buton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Buton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Buton3MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Cargar archivos a BD");

        javax.swing.GroupLayout Buton3Layout = new javax.swing.GroupLayout(Buton3);
        Buton3.setLayout(Buton3Layout);
        Buton3Layout.setHorizontalGroup(
            Buton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Buton3Layout.setVerticalGroup(
            Buton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        Buton2.setBackground(new java.awt.Color(250, 252, 253));
        Buton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Buton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Buton2MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("Cargar Archivo local");

        javax.swing.GroupLayout Buton2Layout = new javax.swing.GroupLayout(Buton2);
        Buton2.setLayout(Buton2Layout);
        Buton2Layout.setHorizontalGroup(
            Buton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Buton2Layout.setVerticalGroup(
            Buton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Arboles Binarios");

        Texto.setText("Texto");
        Texto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Buton.setBackground(new java.awt.Color(250, 252, 253));
        Buton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Buton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButonMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("Cerrar");

        javax.swing.GroupLayout ButonLayout = new javax.swing.GroupLayout(Buton);
        Buton.setLayout(ButonLayout);
        ButonLayout.setHorizontalGroup(
            ButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButonLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButonLayout.setVerticalGroup(
            ButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        Buton4.setBackground(new java.awt.Color(250, 252, 253));
        Buton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Buton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Buton4MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Generar Árbol");

        javax.swing.GroupLayout Buton4Layout = new javax.swing.GroupLayout(Buton4);
        Buton4.setLayout(Buton4Layout);
        Buton4Layout.setHorizontalGroup(
            Buton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Buton4Layout.setVerticalGroup(
            Buton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        Buton5.setBackground(new java.awt.Color(250, 252, 253));
        Buton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Buton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Buton5MouseExited(evt);
            }
        });

        jLabel4.setText("Imprimir Árbol");

        javax.swing.GroupLayout Buton5Layout = new javax.swing.GroupLayout(Buton5);
        Buton5.setLayout(Buton5Layout);
        Buton5Layout.setHorizontalGroup(
            Buton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Buton5Layout.setVerticalGroup(
            Buton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Buton6.setBackground(new java.awt.Color(250, 252, 253));
        Buton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Buton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Buton6MouseExited(evt);
            }
        });

        jLabel5.setText("Limpiar base de datos");

        javax.swing.GroupLayout Buton6Layout = new javax.swing.GroupLayout(Buton6);
        Buton6.setLayout(Buton6Layout);
        Buton6Layout.setHorizontalGroup(
            Buton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Buton6Layout.setVerticalGroup(
            Buton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buton6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Buton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Buton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(Buton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(Buton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void ButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonMouseClicked
        // TODO add your handling code here:
        content.setBackground(new Color(239, 244, 249));
        content.removeAll();

        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_ButonMouseClicked

    private void ButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonMouseEntered
        // TODO add your handling code here:
        Buton.setBackground(new Color(194, 231, 255));
    }//GEN-LAST:event_ButonMouseEntered

    private void ButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonMouseExited
        // TODO add your handling code here:
        Buton.setBackground(new Color(250, 252, 253));
    }//GEN-LAST:event_ButonMouseExited

    private void Buton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton2MouseClicked
        String rutaArchivo = "";

        // Crear un nuevo JFrame para el JFileChooser
        JFrame explorador = new JFrame();
        explorador.setVisible(false);
        explorador.setSize(500, 500);

        // Crear un JFileChooser
        JFileChooser fileChooser = new JFileChooser();

        // Mostrar el diálogo para seleccionar archivos
        int seleccion = fileChooser.showOpenDialog(explorador);

        // Verificar si el usuario seleccionó un archivo
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Obtener el archivo seleccionado
            File selectedFile = fileChooser.getSelectedFile();

            // Obtener la ruta absoluta del archivo y reemplazar las barras inclinadas con dobles barras inclinadas
            rutaArchivo = selectedFile.getAbsolutePath();

            // Mostrar la dirección del archivo seleccionado en la consola
            System.out.println("Dirección del archivo seleccionado: " + rutaArchivo);

            // Llamar al método File_Reader con la ruta del archivo y el componente Texto
            Texto.setText(rutaArchivo);
        } else if (seleccion == JFileChooser.CANCEL_OPTION) {
            // El usuario canceló la operación
            System.out.println("Operación cancelada");
        }
        File_Reader(rutaArchivo, Texto);
        // Cerrar el JFrame del JFileChooser
        explorador.dispose();


    }//GEN-LAST:event_Buton2MouseClicked

    private void Buton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton2MouseEntered
        // TODO add your handling code here:
        Buton2.setBackground(new Color(194, 231, 255));
    }//GEN-LAST:event_Buton2MouseEntered

    private void Buton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton3MouseEntered
        // TODO add your handling code here:
        Buton3.setBackground(new Color(194, 231, 255));
    }//GEN-LAST:event_Buton3MouseEntered

    private void Buton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton4MouseEntered
        // TODO add your handling code here:
        Buton4.setBackground(new Color(194, 231, 255));
    }//GEN-LAST:event_Buton4MouseEntered

    private void Buton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton5MouseEntered
        // TODO add your handling code here:
        Buton5.setBackground(new Color(194, 231, 255));
    }//GEN-LAST:event_Buton5MouseEntered

    private void Buton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton6MouseEntered
        // TODO add your handling code here:
        Buton6.setBackground(new Color(194, 231, 255));
    }//GEN-LAST:event_Buton6MouseEntered

    private void Buton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton2MouseExited
        // TODO add your handling code here:
        Buton2.setBackground(new Color(250, 252, 253));
    }//GEN-LAST:event_Buton2MouseExited

    private void Buton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton3MouseExited
        // TODO add your handling code here:
        Buton3.setBackground(new Color(250, 252, 253));
    }//GEN-LAST:event_Buton3MouseExited

    private void Buton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton4MouseExited
        // TODO add your handling code here:
        Buton4.setBackground(new Color(250, 252, 253));
    }//GEN-LAST:event_Buton4MouseExited

    private void Buton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton5MouseExited
        // TODO add your handling code here:
        Buton5.setBackground(new Color(250, 252, 253));
    }//GEN-LAST:event_Buton5MouseExited

    private void Buton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton6MouseExited
        // TODO add your handling code here:
        Buton6.setBackground(new Color(250, 252, 253));
    }//GEN-LAST:event_Buton6MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buton;
    private javax.swing.JPanel Buton2;
    private javax.swing.JPanel Buton3;
    private javax.swing.JPanel Buton4;
    private javax.swing.JPanel Buton5;
    private javax.swing.JPanel Buton6;
    private javax.swing.JLabel Texto;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
