/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gt.edu.umg.Ventanas;

import gt.edu.umg.MemoryManager.MemoryManager;
import java.awt.Color;
import java.util.List;
import java.util.Random;

/**
 *
 * @author rober
 */
public class Page3 extends javax.swing.JPanel {

    int numBlocks = 7; // Número de bloques de memoria
    int minSize = 8; // Tamaño mínimo de un bloque de memoria
    int maxSize = 64; // Tamaño máximo de un bloque de memoria
    MemoryManager memoryManager = new MemoryManager(numBlocks, minSize, maxSize); // Crear un gestor de memoria con bloques aleatorios
     List<Integer> memoryState = memoryManager.getMemoryBlockSizes();
    int[] memoryStateArray = new int[memoryState.size()];
     

    /**
     * Creates new form Page1
     */
    public Page3() {

        initComponents();
        Panel.setBackground(new Color(250, 252, 253));
        raid();
        Graf();
        

    }

    private void Graf() {

        String memoryState = memoryManager.printMemoryState2();
        
        textArea.setText(memoryState);
        raid();

    }

 
    
    private void raid(){
       
        List<Integer> memoryState = memoryManager.getMemoryBlockSizes(); // Llamar al método getMemoryState()
        memoryStateArray = memoryState.stream().mapToInt(Integer::intValue).toArray();
        
        
         Random random = new Random();

        // Establecer colores diferentes para cada panel para visualización
        /*Memory1.setBackground(Color.GREEN);
        Memory2.setBackground(Color.GREEN);
        Memory3.setBackground(Color.BLUE);
        Memory4.setBackground(Color.YELLOW);
        Memory5.setBackground(Color.ORANGE);
        Memory6.setBackground(Color.CYAN);
        Memory7.setBackground(Color.MAGENTA);
        
        
         */
        
        Memory1.setSize(64, 48);
        Memory2.setSize(64-memoryStateArray[0], 48);
        Memory3.setSize(64-memoryStateArray[1], 48);
        Memory4.setSize(64-memoryStateArray[2], 48);
        Memory5.setSize(64-memoryStateArray[3], 48);
        Memory6.setSize(64-memoryStateArray[4], 48);
        Memory7.setSize(64-memoryStateArray[5], 48);
        Memory8.setSize(64-memoryStateArray[6], 48);
        
        
        
        /*    int Mem = 65;
        Memory1.setSize(64, 48);
        int a = ((Mem / Mem) * random.nextInt(Mem) + 1);
        
        Memory2.setSize(a, 48);
        a = ((Mem / Mem) * random.nextInt(Mem) + 1);
        
        Memory3.setSize(a, 48);
        a = ((Mem / Mem) * random.nextInt(Mem) + 1);
        
        Memory4.setSize(a, 48);
        a = ((Mem / Mem) * random.nextInt(Mem) + 1);
        
        Memory5.setSize(a, 48);
        a = ((Mem / Mem) * random.nextInt(Mem) + 1);
        
        Memory6.setSize(a, 48);
        a = ((Mem / Mem) * random.nextInt(Mem) + 1);
        
        Memory7.setSize(a, 48);
        a = ((Mem / Mem) * random.nextInt(Mem) + 1);
        Memory8.setSize(a, 48);*/
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Buton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtdato = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Memory1 = new javax.swing.JPanel();
        Memory2 = new javax.swing.JPanel();
        Memory3 = new javax.swing.JPanel();
        Memory4 = new javax.swing.JPanel();
        Memory5 = new javax.swing.JPanel();
        Memory6 = new javax.swing.JPanel();
        Memory7 = new javax.swing.JPanel();
        Memory8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textArea = new java.awt.TextArea();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 252, 253));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(250, 252, 253));

        Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Administracion de Memoria");

        Buton.setBackground(new java.awt.Color(250, 252, 253));
        Buton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Buton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButonMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("Cerrar");

        javax.swing.GroupLayout ButonLayout = new javax.swing.GroupLayout(Buton);
        Buton.setLayout(ButonLayout);
        ButonLayout.setHorizontalGroup(
            ButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButonLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButonLayout.setVerticalGroup(
            ButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Primer Ajuste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mejor Ajuste");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Peor Ajuste");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Vaciar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("LLenar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Memory1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Memory1.setPreferredSize(new java.awt.Dimension(44, 2));

        javax.swing.GroupLayout Memory1Layout = new javax.swing.GroupLayout(Memory1);
        Memory1.setLayout(Memory1Layout);
        Memory1Layout.setHorizontalGroup(
            Memory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        Memory1Layout.setVerticalGroup(
            Memory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(Memory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 64, 48));

        Memory2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Memory2.setPreferredSize(new java.awt.Dimension(44, 2));

        javax.swing.GroupLayout Memory2Layout = new javax.swing.GroupLayout(Memory2);
        Memory2.setLayout(Memory2Layout);
        Memory2Layout.setHorizontalGroup(
            Memory2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        Memory2Layout.setVerticalGroup(
            Memory2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(Memory2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 1, 64, 48));

        Memory3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Memory3.setPreferredSize(new java.awt.Dimension(44, 2));

        javax.swing.GroupLayout Memory3Layout = new javax.swing.GroupLayout(Memory3);
        Memory3.setLayout(Memory3Layout);
        Memory3Layout.setHorizontalGroup(
            Memory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        Memory3Layout.setVerticalGroup(
            Memory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(Memory3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 1, 64, 48));

        Memory4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Memory4.setName(""); // NOI18N
        Memory4.setPreferredSize(new java.awt.Dimension(44, 2));

        javax.swing.GroupLayout Memory4Layout = new javax.swing.GroupLayout(Memory4);
        Memory4.setLayout(Memory4Layout);
        Memory4Layout.setHorizontalGroup(
            Memory4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        Memory4Layout.setVerticalGroup(
            Memory4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(Memory4, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 1, 64, 48));

        Memory5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Memory5.setPreferredSize(new java.awt.Dimension(44, 2));

        javax.swing.GroupLayout Memory5Layout = new javax.swing.GroupLayout(Memory5);
        Memory5.setLayout(Memory5Layout);
        Memory5Layout.setHorizontalGroup(
            Memory5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        Memory5Layout.setVerticalGroup(
            Memory5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(Memory5, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 1, 64, 48));

        Memory6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Memory6.setPreferredSize(new java.awt.Dimension(44, 2));

        javax.swing.GroupLayout Memory6Layout = new javax.swing.GroupLayout(Memory6);
        Memory6.setLayout(Memory6Layout);
        Memory6Layout.setHorizontalGroup(
            Memory6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        Memory6Layout.setVerticalGroup(
            Memory6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(Memory6, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 1, 64, 48));

        Memory7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout Memory7Layout = new javax.swing.GroupLayout(Memory7);
        Memory7.setLayout(Memory7Layout);
        Memory7Layout.setHorizontalGroup(
            Memory7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        Memory7Layout.setVerticalGroup(
            Memory7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(Memory7, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 1, 64, 48));

        Memory8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout Memory8Layout = new javax.swing.GroupLayout(Memory8);
        Memory8.setLayout(Memory8Layout);
        Memory8Layout.setHorizontalGroup(
            Memory8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        Memory8Layout.setVerticalGroup(
            Memory8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(Memory8, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 1, 64, 48));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Memoria Principal 512Kb");

        jLabel3.setText("8 Fragmentos de 64Kb");

        jLabel4.setText("64Kb del Sistema");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdato, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Buton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(805, 805, 805))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Buton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        memoryManager.clearMemoryBlocks();
        Graf();
        raid();
        //info.setText("Variable 1: " + variable1 + ", Variable 2: " + variable2);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       memoryManager.firstFit(Integer.valueOf(txtdato.getText()));
        txtdato.setText("");
        Graf();
        raid();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonMouseExited
        // TODO add your handling code here:
        Buton.setBackground(new Color(250, 252, 253));
    }//GEN-LAST:event_ButonMouseExited

    private void ButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonMouseEntered
        // TODO add your handling code here:
        Buton.setBackground(new Color(194, 231, 255));
    }//GEN-LAST:event_ButonMouseEntered

    private void ButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonMouseClicked
        // TODO add your handling code here:
        content.setBackground(new Color(239, 244, 249));
        content.removeAll();

        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_ButonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         memoryManager.bestFit(Integer.valueOf(txtdato.getText()));
        txtdato.setText("");
        Graf();
        raid();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        memoryManager.worstFit(Integer.valueOf(txtdato.getText()));
        txtdato.setText("");
        Graf();
        raid();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buton;
    private javax.swing.JPanel Memory1;
    private javax.swing.JPanel Memory2;
    private javax.swing.JPanel Memory3;
    private javax.swing.JPanel Memory4;
    private javax.swing.JPanel Memory5;
    private javax.swing.JPanel Memory6;
    private javax.swing.JPanel Memory7;
    private javax.swing.JPanel Memory8;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextArea textArea;
    private javax.swing.JTextField txtdato;
    // End of variables declaration//GEN-END:variables

}
